In [ ]:
import torch


In [ ]:
x = torch.randn(3,requires_grad=True)
print(x)

tensor([ 0.2959,  1.0150, -0.6566], requires_grad=True)


In [ ]:
y = x+2
print(y)

z = y*y*3
out = z.mean()
print(z,out)
# z.backward()

tensor([2.2959, 3.0150, 1.3434], grad_fn=<AddBackward0>)
tensor([15.8141, 27.2700,  5.4143], grad_fn=<MulBackward0>) tensor(16.1661, grad_fn=<MeanBackward0>)


In [ ]:
v = torch.tensor([0.1,1.0,0.001],dtype=torch.float32)
z.backward(v) #dz/dx
print(x.grad)

tensor([1.3776e+00, 1.8090e+01, 8.0605e-03])


In [ ]:
x = torch.arange(start = 1 , end = 100 , step = 10)
print(x)

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])


In [ ]:
x_reshape = x.reshape(10,1)
print(x_reshape)

tensor([[ 1],
        [11],
        [21],
        [31],
        [41],
        [51],
        [61],
        [71],
        [81],
        [91]])


In [ ]:
#change the view
z = x.view(5,2)
print(z,z.shape)

tensor([[ 1, 11],
        [21, 31],
        [41, 51],
        [61, 71],
        [81, 91]]) torch.Size([5, 2])


In [ ]:
# z[:,0]=5
print(z,x)

tensor([[ 1, 11],
        [21, 31],
        [41, 51],
        [61, 71],
        [81, 91]]) tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])


In [ ]:
#stack tensors
x_stack = torch.stack([x,x,x,x],dim=0)
print(x_stack)

tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])


In [ ]:
xvstack = torch.vstack([x,x,x,x])
print(xvstack)

tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])


In [ ]:
xhstack = torch.hstack([x,x,x,x])
print(xhstack)

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91,  1, 11, 21, 31, 41, 51, 61, 71,
        81, 91,  1, 11, 21, 31, 41, 51, 61, 71, 81, 91,  1, 11, 21, 31, 41, 51,
        61, 71, 81, 91])


In [ ]:
#squeez and unsqeez
z = z.reshape(1,1,10)
print(z,z.shape)
z_sq = z.squeeze()
print(z_sq,z_sq.shape)
z_unsq = z_sq.unsqueeze(dim=0)
print(z_unsq,z_unsq.shape)

tensor([[[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]]]) torch.Size([1, 1, 10])
tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]) torch.Size([10])
tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]]) torch.Size([1, 10])


In [ ]:
#permute
x = torch.randn(2,3,5)
print(x.shape)
x_permute = x.permute(2,0,1)
print(x_permute.shape)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


# ***Pytorch with numppy***


In [ ]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
tensor = tensor.type(torch.float32)
print(array,tensor,tensor.dtype)

[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.]) torch.float32


In [ ]:
#CHANGE VALUE OF ARRAY
array = array+1
print(array,tensor)

[2. 3. 4. 5. 6. 7. 8.] tensor([1., 2., 3., 4., 5., 6., 7.])


In [ ]:
#tensor to numpy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
print(tensor,numpy_tensor)

tensor([1., 1., 1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#pytorch reproducibility :-  tryng to take random from random value

random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)


tensor([[0.9159, 0.0462, 0.2029, 0.6212],
        [0.1892, 0.4053, 0.1219, 0.9054],
        [0.7573, 0.6493, 0.7324, 0.6273]])
tensor([[0.9206, 0.0984, 0.6029, 0.7527],
        [0.8328, 0.1279, 0.2196, 0.1141],
        [0.0980, 0.4596, 0.3145, 0.5529]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#make some random but reproduceble

random_seed = 42
torch.manual_seed(random_seed)
random_tensor_c = torch.rand(3,4)
torch.manual_seed(random_seed)
random_tensor_d = torch.rand(3,4)
print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
 # running tensors on gpus
 !nvidia-smi


Sun Sep 22 11:07:19 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8              10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
#cheak for gpu access in pytorch
import torch
torch.cuda.is_available()

True

In [ ]:
#setup gpu
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count the no of gpu
torch.cuda.device_count()

1

In [ ]:
a = torch.tensor([1,2,3])
a.device

device(type='cpu')

In [ ]:
a.to(device)

tensor([1, 2, 3], device='cuda:0')